# -*- coding: utf-8 -*-

""" Default parameters to get table and light curves data using astroquery. """


DEFAULT_PARAMS = {
    "q1_q17_dr25_stellar": {
        "columns": {
            "kepid": "KIC Identification Number",
            "tm_designation": "2MASS Designation",
            "ra": "RA Value [decimal degrees]",
            "dec": "Dec Value [decimal degrees]",
            "teff": "Stellar Effective Temperature Value [K]",
            "logg": "Stellar Surface Gravity Value [log10(cm/s**2)]",
            "feh": "Stellar Metallicity Value [dex]",
            "radius": "Stellar Radius Value [Solar radii]",
            "mass": "Stellar Mass Value [Solar mass]",
            "dens": "Stellar Density Value [g/cm**3]",
            "dist": "Distance Value [pc]",
            "av": "Av Extinction Value [mags]",
            "kepmag": "Kepler-band Magnitude Value [mag]",
            "nconfp": "Number of Associated Confirmed Planets",
            "nkoi": "Number of Associated KOIs",
            "ntce": "Number of Associated TCEs",
            "st_quarters": "Bits of Observed Quarters",
            "st_vet_date": "Vetting Status Date",
        },
        "where": "st_quarters like '%1%'",
    },
    "cumulative": {
        "columns": {
            "kepid": "KIC Identification Number",
            "kepoi_name": "KOI Name",
            "kepler_name": "Kepler Name",
            "ra": "RA Value [decimal degrees]",
            "dec": "Dec Value [decimal degrees]",
            "koi_disposition": "Exoplanet Archive Disposition",
            "koi_score": "Disposition Score",
            "koi_fpflag_nt": "Not Transit-Like Flag",
            "koi_fpflag_ss": "Stellar Eclipse Flag",
            "koi_fpflag_co": "Nearby Star Flag",
            "koi_fpflag_ec": "Contamination Flag",
            "koi_period": "Orbital Period (days)",
            "koi_time0bk": "Transit Epoch",
            "koi_time0": "Transit Epoch in BJD",
            "koi_eccen": "Eccentricity",
            "koi_duration": "Transit Duration (hours)",
            "koi_ingress": "Ingress Duration (hours)",
            "koi_depth": "Transit Depth (parts per million)",
            "koi_ror": "Planet-Star Radius Ratio",
            "koi_srho": "Fitted Stellar Density [g/cm*3]",
            "koi_prad": "Planetary Radius (Earth radii)",
            "koi_incl": "Inclination (deg)",
            "koi_teq": "Equilibrium Temperature (Kelvin)",
            "koi_dor": "Planet-Star Distance over Star Radius",
            "koi_model_snr": "Transit Signal-to-Noise",
            "koi_count": "Number of Planets",
            "koi_num_transits": "Number of Transits",
            "koi_tce_plnt_num": "TCE Planet Number",
            "koi_quarters": "Quarters",
            "koi_kepmag": "Kepler-band (mag)",
            "koi_vet_date": "Vetting Status Date",
        },
        "where": "st_quarters like '%1%'",
    },
    "exoplanets": {
        "columns": {
            "pl_hostname": "Host Name",
            "pl_letter": "Planet Letter",
            "pl_name": "Planet Name",
            "pl_discmethod": "Discovery Method",
            "pl_controvflag": "Controversial Flag",
            "pl_pnum": "Number of Planets in System",
            "pl_orbper": "Orbital Period [days]",
            "pl_orbsmax": "Orbit Semi-Major Axis [au])",
            "pl_orbeccen": "Eccentricity",
            "pl_orbincl": "Inclination [deg]",
            "pl_bmassj": "Planet Mass or M*sin(i) [Jupiter mass]",
            "pl_radj": "Planet Radius [Jupiter radii]",
            "pl_dens": "Planet Density [g/cm**3]",
            "pl_kepflag": "Kepler Field Flag",
            "ra": "RA [decimal degrees]",
            "dec": "Dec [decimal degrees]",
            "st_dist": "Distance [pc]",
            "gaia_dist": "Gaia Distance [pc]",
            "st_optmag": "Optical Magnitude [mag]",
            "st_teff": "Effective Temperature [K]",
            "st_mass": "Stellar Mass [Solar mass]",
            "st_rad": "Stellar Radius [Solar radii]",
            "pl_facility": "Discovery Facility",
        },
        "where": None,
    },
}
